# Generated by Django 4.0.3 on 2022-03-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_Auth_Token', models.CharField(max_length=50)),
                ('auth_key', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=50)),
                ('win', models.IntegerField(null=True)),
                ('lose', models.IntegerField(null=True)),
                ('taken', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=50)),
                ('problem', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=50)),
                ('_id', models.IntegerField(null=True)),
                ('grade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=50)),
                ('_id', models.IntegerField(null=True)),
                ('_from', models.IntegerField(null=True)),
            ],
        ),
    ]
